### ISSUE TITLE
Add or remove section

### ISSUE THREAD

**Issue by an-schall** [themefisher/meghna-hugo#147]
Hi there,

I am rather new to hugo and I like this theme a lot. Thanks for the great work. However, I have a fundamental question: Is there a way to

1. Add or remove sections?
2. Change the layout of some sections (i.e. I tried use one of the team member items in the about section)?

In general, to edit content, one would change the respective *.yml file in /data/en/?

Thanks in advance!

**Comment by developer-evan** [comment]
Hello @an-schall,

Thanks for using our theme. You can simply remove a section by `enable: false` from the homepage.yml file. And if you want to duplicate or create a new section, then you need to edit the index.html file and clone a section with a different name. say you want to clone the team section, then clone it and change the name to team2. otherwise, it will show the data from the team1 section.

I would also like to know you that if you want to customize any Hugo theme, we are available for hire. contact us at mehedi@themefisher.com. and mention that you are from the Github community to get special support. thanks for being with Themefisher.
