### ISSUE TITLE
Won't build when deploying to Firebase properly

### ISSUE THREAD

**Issue by Origin-Botanica** [themefisher/meghna-hugo#181]
I am using your template to build a simple landing page for my company but the problem is that when I deploy to Firebase the website looks terrible. I build and deploy using these lines of code.

`hugo --themesDir ../.. && firebase deploy `

This is what the page looks like after deployment. I checked to see if the development server was working correctly and it is. I'm only having problems when I deploy to Firebase. 

Can you help me with this?

<img width="1792" alt="Screen Shot 2021-12-29 at 12 51 28 AM" src="https://user-images.githubusercontent.com/96795302/147631416-e03285fd-e2f6-40df-9f10-a376e0d27877.png">

**Comment by tfsomrat** [comment]
Hello @Origin-Botanica 
I think your images and CSS are missing because of the baseURL. You have a live URL after deploying it on firebase. You just need to copy this URL and put it on the `config.toml` files `baseURL` field.  then deploy it again. and see the output. Let me know is it working or not. Thank you

**Comment by tfsomrat** [comment]
Hey @Origin-Botanica 

Hope your problem has been resolved, I am closing this issue, if you have any queries, you can re-open this issue or create a new one. thanks
